version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 3000:27017
    volumes:
      - db-volume:/var/db

  back-end-main:
    restart: always
    build:
      context: ../back-end-main
    command: npm start
    ports:
      - 3001:1337
    environment:
      - MONGODB_PORT=3000
      - backend.env
    links:
      - mongo

  back-end-color-of-the-day:
    restart: always
    build:
      context: ../back-end-color-of-the-day
    command: npm start
    ports: 
      - 3002:1338
    environment:
      - MONGODB_PORT=3000
      - backend.env
    links:
      - mongo

  front-end:
    restart: always
    build:
      context: ../front-end
    command: npm start
    ports: 
      - 3003:3000
    environment: 
      - BACKEND_PORT_MAIN=3000
      - BACKEND_PORT_COLOR_OF_THE_DAY=3001
    links:
      - back-end-main
      - back-end-color-of-the-day

volumes:
  db-volume: